### ISSUE TITLE
Remove regex from metadata queries

### ISSUE THREAD

**Issue by jtcohen6** [fishtown-analytics/dbt-presto#34]
@WangSleep commented on [Thu Nov 19 2020](https://github.com/fishtown-analytics/dbt/issues/2900)

###  When i excute "dbt docs generate" on CLI .it dosen't work . 

**it's error message :** 
_PrestoQueryError(type=INTERNAL_ERROR, name=OPTIMIZER_TIMEOUT, message="The optimizer exhausted the time limit of 180000 ms", query_id=20201110_082631_11221_7vjyv)_

i can excute "dbt deug" , "dbt test" ,"dbt run" on CLI . but "dbt docs generate" alone can't 

Can you solve my problem?

thanks a lot ~~~😊

---

@WangSleep commented on [Thu Nov 19 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-730208377)

### I found out when I performed "dbt docs generate" , it will excute this sql 

`select
      table_catalog as database,
      table_name as name,
      table_schema as schema,
      case when table_type = 'BASE TABLE' then 'table'
           when table_type = 'VIEW' then 'view'
           else table_type
      end as table_type
    from "hive".INFORMATION_SCHEMA.tables
    where regexp_like(table_schema, '(?i)\ADatebase\Z')`

**Too many resources are required, and execution time is too long to cause a timeout 。**

**Could you tell me what can be solved?  thanks a lot**

---

@jtcohen6 commented on [Thu Nov 19 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-730409530)

Hey @WangSleep, which database / adapter plugin are you using? It sounds like the catalog query—which dbt uses to grab metadata, populate `catalog.json`, and thereby feed information into the docs site—may be inefficient as currently implemented on this adapter.

---

@WangSleep commented on [Thu Nov 19 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-730797281)

> Hey @WangSleep, which database / adapter plugin are you using? It sounds like the catalog query—which dbt uses to grab metadata, populate `catalog.json`, and thereby feed information into the docs site—may be inefficient as currently implemented on this adapter.

yeh . 

We query by configuring presto-python-client, which I know is for docs, but python_presto query "hive". INFORMATION_SCHEMA is slow. This causes a timeout. Later I found out that I used lore-zeppelin, which was based on jdbc, and I could query. It takes about 5 minutes.

thanks a lot ~

---

@jtcohen6 commented on [Fri Nov 20 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-731423173)

I'm still a bit confused. Are you using [dbt-presto](https://github.com/fishtown-analytics/dbt-presto)? What's the output when you run `dbt --version`?

---

@WangSleep commented on [Sun Nov 22 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-731903410)

> I'm still a bit confused. Are you using [dbt-presto](https://github.com/fishtown-analytics/dbt-presto)? What's the output when you run `dbt --version`?

hi , bro ! 
yes . 
I'm using it . dbt --version : 0.18.1

---

@jtcohen6 commented on [Mon Nov 23 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-732278267)

We haven't released dbt-presto v0.18.1 yet (which is on us), and [`presto__get_catalog`](https://github.com/fishtown-analytics/dbt-presto/blob/master/dbt/include/presto/macros/catalog.sql) as implemented in that plugin looks different from the query snippet you pasted above. (In fact, your snippet doesn't look like any of the `get_catalog` queries familiar to me.)

So... I'm still confused as to which dbt plugin you're using :)

---

@WangSleep commented on [Mon Nov 23 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-732624946)

> We haven't released dbt-presto v0.18.1 yet (which is on us), and [`presto__get_catalog`](https://github.com/fishtown-analytics/dbt-presto/blob/master/dbt/include/presto/macros/catalog.sql) as implemented in that plugin looks different from the query snippet you pasted above. (In fact, your snippet doesn't look like any of the `get_catalog` queries familiar to me.)
> 
> So... I'm still confused as to which dbt plugin you're using :)

hi .  @jtcohen6  

FYI

This is the version I installed  :) 

![image](https://user-images.githubusercontent.com/19337980/100043242-f309e600-2e47-11eb-8dd9-5476dd65280e.png)

---

@jtcohen6 commented on [Tue Nov 24 2020](https://github.com/fishtown-analytics/dbt/issues/2900#issuecomment-733000123)

Ok, this makes much more sense now. Appreciate the clarification!

The snippet you included comes from [`presto__list_relations_without_caching`](https://github.com/fishtown-analytics/dbt-presto/blob/0899fc3987c7dd3a676826a8489f32ee4797922e/dbt/include/presto/macros/adapters.sql#L41-L55). I'm not sure why it only times out on `dbt docs generate`, since that's a query that should run at the start of all invocations.

I'm going to transfer this issue to the dbt-presto repo, where we can discuss if there is a more performant way to write that metadata introspection. Out of curiosity, how many objects are in your `"hive"` catalog?

**Comment by WangSleep** [comment]
thanks ~ 

about 4000 - 5000 metadata table in hive and about 100 database information when i need to query :)

**Comment by jtcohen6** [comment]
I'm pretty sure the culprit here is `presto_ilike`, which performs regex in the filter and likely requires scanning _all_ tables in the metastore.

Several months ago, we made the decision to switch dbt-snowflake from performing ilike queries of `information_schema.tables` to instead use `show terse objects in schema` (https://github.com/fishtown-analytics/dbt/pull/2322).

Presto supports both `information_schema` queries and `show` for schemas, tables, and columns. It would be worth doing some performance benchmarking to check if one is faster than the other. The **big** change, that we should make regardless, is to remove the regex filter and replace it with an equality match, both in `list_relations_without_caching` and `get_columns_in_relation`.

As in dbt-snowflake, it will require a bit of extra handling to first figure out the right quoting and casing of available schemas.

**Comment by WangSleep** [comment]
> I'm pretty sure the culprit here is `presto_ilike`, which performs regex in the filter and likely requires scanning _all_ tables in the metastore.
> 
> Several months ago, we made the decision to switch dbt-snowflake from performing ilike queries of `information_schema.tables` to instead use `show terse objects in schema` ([fishtown-analytics/dbt#2322](https://github.com/fishtown-analytics/dbt/pull/2322)).
> 
> Presto supports both `information_schema` queries and `show` for schemas, tables, and columns. It would be worth doing some performance benchmarking to check if one is faster than the other. The **big** change, that we should make regardless, is to remove the regex filter and replace it with an equality match, both in `list_relations_without_caching` and `get_columns_in_relation`.
> 
> As in dbt-snowflake, it will require a bit of extra handling to first figure out the right quoting and casing of available schemas.



I modified the **adapters.sql** and **catalog.sql** files。

**adapters.sql** : use '=' relpace 'ilike'
**catalog.sql** :  add two 'where' Conditions.

It now takes about 2 minutes to execute。so , thansk a lot .

For now, it's settled 。

thank you vary much .and finally ，snapshot materialization not implemented for presto。It's such a pity    @@/(ㄒoㄒ)/~~

@jtcohen6
